language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
    - shards
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_SHARDS_DIR=shards
    - BINARYBUILDER_AUTOMATIC_APPLE=true
    - BINARYBUILDER_USE_CCACHE=true
  # Our build takes too long for one job, so split targets across multiple jobs
  matrix:
    - TARGET=x86_64-linux-gnu
    # - TARGET=i686-linux-gnu
    # - TARGET=aarch64-linux-gnu
    # - TARGET=arm-linux-gnueabihf
    # - TARGET=powerpc64le-linux-gnu
    # - TARGET=x86_64-apple-darwin14
    # - TARGET=x86_64-w64-mingw32
    # - TARGET=i686-w64-mingw32
sudo: required

jobs:
  include:
    - stage: regenerate build.jl
      script: julia --color=yes build_tarballs.jl --only-buildjl
      if: tag IS present

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'

script:
  - julia build_tarballs.jl --llvm-reldbg --llvm-keep-tblgen $TARGET
  - julia build_tarballs.jl --llvm-release $TARGET

deploy:
  provider: releases
  api_key:
    secure: uDQJC+vaGHASeummZr1aibqEn6YC1JMqx92skCjB616pPPoW7c8bi0QqW3ddhGOuvf+DSugaY5GD/J1NSmOUpgRZ0y0p6Y0LgKKmJUYeGOZ7EqvhaQbFDFU6JEBalyKi9e2vH0usjKZZGJb/kDDlUTbRhpeU5jekvEzxS8vVW0b537QZjmM7tI0f/jbCXR/4QjJXEJd7CFV3YGVnI07r51e3moBeUXL2esxQleuiOvjIHehxZ8wwPKCAbnWRdxKY7DwEFMQY75W9vh02nl8Sh1iCNH5mz3xyMIoBWMgIULxNyNzSxJM9UW1PBYxCv43czB0L6ECZyPORupYooHibVfq5L9NyUTA/wS4E0jYj+agMq7XvQo5MjDq4l1a0Ph+VEirBpsEzTFqFPRkTaxr43Bb9nyHifCmCbikKLNWLXAKyipPQBB7pVyXR+rZKBVNlzqOPf6JTzDvWZeHce9qyQtMyuvpULXDFvNxgKc6DucH4A6l2mJAuRjlifnPwVWzCd6nwAdcdLpy14lUFHKjPKDnSrd0/+zfE5N3tPWyMbn73CrMKnaq/u5z94i72gtoAFvkxPnd66PtKYV+pOotXeFmpjlDF545MLwjx/HfC1evI5Vwfe02otMGV5ocyOUNjemday6Y/42PO8I5P/Yzj6mvUem8YlqPDoZPcc0PKBS8=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: cdsousa/LLVMBuilder
    tags: true
